### ISSUE TITLE
Automatic Image Handling

### ISSUE THREAD

**Issue by pearcemichal** [tomhrtly/FlexCarousel.js#19]
Before I start, I just wanted to say thank you for doing this. I've been struggling with getting slick to work on my flexbox based site, and had to to a bunch of hacky workarounds. Your system seems like its going to be a much better solution. 

Now, on to the issues:

When I first tried this, it did not handle images very well, and I fixed it by adding my own css to the images

```
    .carousel img {
    	max-width: 100%;
    	display: block;
    	margin: 0 auto;
    }
```

However, after looking through the code, it does have CSS in place to handle images, but it is not applied by default. Based on what I can tell, you would have to manually add the fc-image class to the parent of any images, since there is not code to apply the fc-image class automatically. 

Is there a reason you can't just add css that will style images by default, such as 

```
.fc-slide img {
  display: block;
  height: auto;
  margin: 0 auto;
  max-width: 100%;
}
```

(the margin: 0 auto is just to make the images center aligned)

Or is there a initialization option I am missing? 

Also, some proper documentation would be appreciated. I had to look up the code pen on the linked website just to figure out how to initialize the carousel. 

EDIT: Just noticed you have the documentation in a separate project. I still think you should at least add the basic initialization example to the readme, and then link to the rest of the documentation under getting started. 

I was thinking of taking a stab at making these changes myself, but I figured I would ask first.

**Comment by tomhrtly** [comment]
No problem! I created this small plugin mainly because I wanted a carousel that worked similar to Slick without the jQuery dependency and thought it would be a good challenge.

> Is there a reason you can't just add css that will style images by default, such as
```
.fc-slide img {
  display: block;
  height: auto;
  margin: 0 auto;
  max-width: 100%;
}
```

Great idea, I actually forgot I made an `fc-image` class, I can probably just change the selector to what you have above.

I don't want to add a margin though as not everyone will want their images to be centered, just because developers will want to be able to add different content without having to fight opinionated styles.

Feel free to open a PR for this. I will also make some documentation improvements based on your comments as well, thanks!
